when@prod: &prod
  framework:
    rate_limiter:
      login:
        policy: 'token_bucket'
        limit: 30
        rate: { interval: '1 second', amount: 1 }
      upload:
        policy: 'token_bucket'
        limit: 30
        rate: { interval: '1 second', amount: 1 }
      supportTicket:
        policy: 'token_bucket'
        limit: 30
        rate: { interval: '30 second', amount: 1 }
      storeLocationChange:
        policy: 'token_bucket'
        limit: 5
        rate: { interval: '1 hour', amount: 1 }

when@dev: *prod

when@test:
  framework:
    rate_limiter:
      login:
        policy: 'no_limit'
        limit: 0
      storeLocationChange:
        policy: 'no_limit'
        limit: 0
