sensio_framework_extra:
  router:
    annotations: false # Required to have no conflict with Symfony Router
  request:
    # We still need this one feature for FOSRESTBundle
    # currently waiting for that to move on, which seems to be quite complicated:
    # https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2354
    converters: true
  view:
    annotations: false
  cache:
    annotations: false
  security:
    annotations: false
