services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
          string $siteEnvironment: !php/const SITE_ENVIRONMENT

    Foodsharing\:
        resource: '../../src/*'
        exclude:
         - '../../src/Lib/{Flourish,Caching.php,View/v*}'
         - '../../src/Dev'
         - '../../src/Kernel.php'
         - '../../src/Modules/{PushNotification/Notification,Foodsaver/Profile.php,Message/Message.php}'
         - '../../src/Modules/Uploads/DTO/'
         - '../../src/RestApi/Models/'

    Foodsharing\Lib\Session:
        calls:
        - [initIfCookieExists]

    markdown.nohtml:
        class: Parsedown
        calls:
            - ['setSafeMode', [true]]
            - ['setMarkupEscaped', [false]]
            - ['setBreaksEnabled', [true]]

    Parsedown: '@markdown.nohtml'

    HTMLPurifier: '@exercise_html_purifier.default'

    BounceMailHandler\BounceMailHandler:
        properties:
            mailhost: !php/const BOUNCE_IMAP_HOST
            mailboxUserName: !php/const BOUNCE_IMAP_USER
            mailboxPassword: !php/const BOUNCE_IMAP_PASS
            port: !php/const BOUNCE_IMAP_PORT
            service: 'imap'
            serviceOption: !php/const BOUNCE_IMAP_SERVICE_OPTION
            boxname: 'INBOX'
            unprocessedBox: !php/const BOUNCE_IMAP_UNPROCESSED_BOX
            maxMessages: 10000
            verbose: 0

    Twig\Extra\Intl\IntlExtension: ~

    GuzzleHttp\Client:

    Foodsharing\Lib\BigBlueButton:
        bind:
            $url: !php/const BBB_DOMAIN
            $secret: !php/const BBB_SECRET
            $dialin: !php/const BBB_DIALIN
