ueber-uns:
  path: /ueber-uns
  controller: Foodsharing\Modules\Content\ContentController::show
  defaults:
    name: about

fuer-unternehmen:
  path: /fuer-unternehmen
  controller: Foodsharing\Modules\Content\ContentController::show
  defaults:
    name: fuer_unternehmen

fairteilerrettung:
  path: /fairteilerrettung
  controller: Foodsharing\Modules\Content\ContentController::show
  defaults:
    name: fairteilerrettung

impressum:
  path: /impressum
  controller: Foodsharing\Modules\Content\ContentController::show
  defaults:
    name: impressum
