<?php

namespace Flourish;

/**
 * Wraps the session control functions and the `$_SESSION` superglobal for a more consistent and safer API.
 *
 * A `Cannot send session cache limiter` warning will be triggered if ::open(),
 * ::add(), ::clear(), ::delete(), ::get() or ::set() is called after output has
 * been sent to the browser. To prevent such a warning, explicitly call ::open()
 * before generating any output.
 *
 * @copyright  Copyright (c) 2007-2012 Will Bond, others
 * @author     Will Bond [wb] <will@flourishlib.com>
 * @author     Alex Leeds [al] <alex@kingleeds.com>
 * @license    http://flourishlib.com/license
 *
 * @see       http://flourishlib.com/fSession
 *
 * @version    1.0.0b22
 * @changes    1.0.0b22  Fixed ::destroy() to no longer call ::regenerateID() since it fails after a session is destroyed [wb, 2012-09-20]
 * @changes    1.0.0b21  Changed ::regenerateID() to not fail silently if the session has not been opened yet [wb, 2012-09-15]
 * @changes    1.0.0b20  Fixed bugs with ::reset() introduced in 1.0.0b19 [wb, 2011-08-23]
 * @changes    1.0.0b19  Fixed some session warning messages for PHP 5.1.6 [wb, 2011-07-29]
 * @changes    1.0.0b18  Added support for storing session data in memcache, redis and databases using fCache and ::setBackend() [wb, 2011-06-21]
 * @changes    1.0.0b17  Updated ::ignoreSubdomain() to use `$_SERVER['HTTP_HOST']` when `$_SERVER['SERVER_NAME']` is not set [wb, 2011-02-01]
 * @changes    1.0.0b16  Changed ::delete() to return the value of the key being deleted [wb, 2010-09-19]
 * @changes    1.0.0b15  Added documentation about `[sub-key]` syntax [wb, 2010-09-12]
 * @changes    1.0.0b14  Backwards Compatibility Break - ::add(), ::delete(), ::get() and ::set() now interpret `[` and `]` as array shorthand and thus they can not be used in keys - added `$beginning` parameter to ::add(), added ::remove() method [wb, 2010-09-12]
 * @changes    1.0.0b13  Fixed a bug that prevented working with existing sessions since they did not have the `fSession::expires` key [wb, 2010-08-24]
 * @changes    1.0.0b12  Changed ::enablePersistence() to always regenerate the session ID, which ensures the function works even if the ID has already been regenerated by fAuthorizaton [wb, 2010-08-21]
 * @changes    1.0.0b11  Updated the class to make sure ::enablePersistence() is called after ::ignoreSubdomain(), ::setLength() and ::setPath() [wb, 2010-05-29]
 * @changes    1.0.0b10  Fixed some documentation bugs [wb, 2010-03-03]
 * @changes    1.0.0b9   Fixed a bug in ::destroy() where sessions weren't always being properly destroyed [wb, 2009-12-08]
 * @changes    1.0.0b8   Fixed a bug that made the unit tests fail on PHP 5.1 [wb, 2009-10-27]
 * @changes    1.0.0b7   Backwards Compatibility Break - Removed the `$prefix` parameter from the methods ::delete(), ::get() and ::set() - added the methods ::add(), ::enablePersistence(), ::regenerateID() [wb+al, 2009-10-23]
 * @changes    1.0.0b6   Backwards Compatibility Break - the first parameter of ::clear() was removed, use ::delete() instead [wb, 2009-05-08]
 * @changes    1.0.0b5   Added documentation about session cache limiter warnings [wb, 2009-05-04]
 * @changes    1.0.0b4   The class now works with existing sessions [wb, 2009-05-04]
 * @changes    1.0.0b3   Fixed ::clear() to properly handle when `$key` is `NULL` [wb, 2009-02-05]
 * @changes    1.0.0b2   Made ::open() public, fixed some consistency issues with setting session options through the class [wb, 2009-01-06]
 * @changes    1.0.0b    The initial implementation [wb, 2007-06-14]
 */
class fSession
{
	/**
	 * The length for a normal session.
	 */
	private static ?int $normal_timespan = null;

    /**
	 * If the session is open.
	 *
	 * @var bool
	 */
	private static bool $open = false;

	/**
	 * The length for a persistent session cookie - one that survives browser restarts.
	 *
	 * @var int
	 */
	private static ?int $persistent_timespan = null;

	/**
	 * If the session ID was regenerated during this script.
	 *
	 * @var bool
	 */
	private static bool $regenerated = false;

	/**
	 * Closes the session for writing, allowing other pages to open the session.
	 */
	public static function close(): void
    {
		if (!self::$open) {
			return;
		}

		session_write_close();
		unset($_SESSION);
		self::$open = false;
	}

	/**
	 * Destroys the session, removing all values.
	 */
	public static function destroy(): void
    {
		self::open();
		$_SESSION = [];
		unset($_SESSION);
		if (isset($_COOKIE[session_name()])) {
			$params = session_get_cookie_params();
			setcookie(session_name(), '', ['expires' => time() - 43200, 'path' => $params['path'], 'domain' => $params['domain'], 'secure' => $params['secure']]);
		}
		session_destroy();
	}

	/**
	 * Changed the session to use a time-based cookie instead of a session-based cookie.
	 *
	 * The length of the time-based cookie is controlled by ::setLength(). When
	 * this method is called, a time-based cookie is used to store the session
	 * ID. This means the session can persist browser restarts. Normally, a
	 * session-based cookie is used, which is wiped when a browser restart
	 * occurs.
	 *
	 * This method should be called during the login process and will normally
	 * be controlled by a checkbox or similar where the user can indicate if
	 * they want to stay logged in for an extended period of time.
	 */
	public static function enablePersistence(): void
    {
		if (self::$persistent_timespan === null) {
			throw new fException(
				'The method %1$s must be called with the %2$s parameter before calling %3$s',
				self::class . '::setLength()',
				'$persistent_timespan',
				self::class . '::enablePersistence()'
			);
		}

		$current_params = session_get_cookie_params();

		$params = [self::$persistent_timespan, $current_params['path'], $current_params['domain'], $current_params['secure']];

		call_user_func_array('session_set_cookie_params', $params);

		self::open();

		$_SESSION['fSession::type'] = 'persistent';

		session_regenerate_id();
		self::$regenerated = true;
	}

	/**
	 * Gets data from the `$_SESSION` superglobal.
	 *
	 * @param string $key            The name to get the value for - array elements can be accessed via `[sub-key]` syntax, and thus `[` and `]` can not be used in key names
	 * @param  mixed  $default_value  The default value to use if the requested key is not set
	 *
	 * @return mixed  The data element requested
	 */
	public static function get(string $key, mixed $default_value = null): mixed
    {
		self::open();

        return $_SESSION[$key] ?? $default_value;
    }

	/**
	 * Opens the session for writing, is automatically called by ::clear(), ::get() and ::set().
	 *
	 * A `Cannot send session cache limiter` warning will be triggered if this,
	 * ::add(), ::clear(), ::delete(), ::get() or ::set() is called after output
	 * has been sent to the browser. To prevent such a warning, explicitly call
	 * this method before generating any output.
	 *
	 * @param bool $cookie_only_session_id  If the session id should only be allowed via cookie - this is a security issue and should only be set to `FALSE` when absolutely necessary
	 */
	public static function open(bool $cookie_only_session_id = true): void
    {
		if (self::$open) {
			return;
		}

		self::$open = true;

		if (self::$normal_timespan === null) {
			self::$normal_timespan = ini_get('session.gc_maxlifetime');
		}

		// If the session is already open, we just piggy-back without setting options
		if (!isset($_SESSION)) {
			if ($cookie_only_session_id) {
				ini_set('session.use_cookies', 1);
				ini_set('session.use_only_cookies', 1);
			}

			session_start();
		}

		// If the session has existed for too long, reset it
		if (isset($_SESSION['fSession::expires']) && $_SESSION['fSession::expires'] < $_SERVER['REQUEST_TIME']) {
			$_SESSION = [];
			self::regenerateID();
		}

		if (!isset($_SESSION['fSession::type'])) {
			$_SESSION['fSession::type'] = 'normal';
		}

		// We store the expiration time for a session to allow for both normal and persistent sessions
		if ($_SESSION['fSession::type'] == 'persistent' && self::$persistent_timespan) {
			$_SESSION['fSession::expires'] = $_SERVER['REQUEST_TIME'] + self::$persistent_timespan;
		} else {
			$_SESSION['fSession::expires'] = $_SERVER['REQUEST_TIME'] + self::$normal_timespan;
		}
	}

	/**
	 * Regenerates the session ID, but only once per script execution.
	 *
	 * @internal
	 */
	public static function regenerateID(): void
    {
		if (!self::$regenerated) {
			self::open();
			if (!session_regenerate_id(true)) {
				throw new fException('There was an error regenerating the session id');
			}
			self::$regenerated = true;
		}
	}

	/**
	 * Resets the configuration of the class.
	 *
	 * @internal
	 */
	public static function reset(): void
    {
		self::$normal_timespan = null;
		self::$persistent_timespan = null;
		self::$regenerated = false;
		self::destroy();
		self::close();
	}

	/**
	 * Sets data to the `$_SESSION` superglobal.
	 *
	 * @param string $key     The name to save the value under - array elements can be modified via `[sub-key]` syntax, and thus `[` and `]` can not be used in key names
	 * @param  mixed  $value   The value to store
	 */
	public static function set(string $key, mixed $value): void
    {
		self::open();

        $_SESSION[$key] = $value;
	}

	/**
	 * Sets the minimum length of a session - PHP might not clean up the session data right away once this timespan has elapsed.
	 *
	 * Please be sure to set a custom session path via ::setPath() to ensure
	 * another site on the server does not garbage collect the session files
	 * from this site!
	 *
	 * Both of the timespan can accept either a integer timespan in seconds,
	 * or an english description of a timespan (e.g. `'30 minutes'`, `'1 hour'`,
	 * `'1 day 2 hours'`).
	 *
	 * @param int|string $normal_timespan      The normal, session-based cookie, length for the session
	 * @param int|string|null $persistent_timespan  The persistent, timed-based cookie, length for the session - this is enabled by calling ::enabledPersistence() during login
	 */
	public static function setLength(int|string $normal_timespan, int|string $persistent_timespan = null): void
    {
		if (self::$open || isset($_SESSION)) {
			throw new fException(
				'%1$s must be called before any of %2$s, %3$s, %4$s, %5$s, %6$s, %7$s or %8$s',
				self::class . '::setLength()',
				self::class . '::add()',
				self::class . '::clear()',
				self::class . '::enablePersistence()',
				self::class . '::get()',
				self::class . '::open()',
				self::class . '::set()',
				'session_start()'
			);
		}

		$seconds = (!is_numeric($normal_timespan)) ? strtotime($normal_timespan) - time() : $normal_timespan;
		self::$normal_timespan = $seconds;

		if ($persistent_timespan) {
			$seconds = (!is_numeric($persistent_timespan)) ? strtotime($persistent_timespan) - time() : $persistent_timespan;
			self::$persistent_timespan = $seconds;
		}

		ini_set('session.gc_maxlifetime', $seconds);
	}

	/**
	 * Forces use as a static class.
	 */
	private function __construct()
	{
	}
}

/*
 * Copyright (c) 2007-2012 Will Bond <will@flourishlib.com>, others
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
