### Compatibility endpoints
index:
  path: /
  controller: Foodsharing\Entrypoint\IndexController

xhr:
  path: /xhr
  controller: Foodsharing\Entrypoint\XhrController

xhrapp:
  path: /xhrapp
  controller: Foodsharing\Entrypoint\XhrAppController

website:
  type: attribute
  prefix: /
  resource:
    path: ../src/Modules/
    namespace: Foodsharing\Modules

mock:
  type: attribute
  prefix: /mock
  resource:
    path: ../src/Mock/
    namespace: Foodsharing\Mock
  condition: "'%kernel.environment%' in ['dev', 'test']"
