website:
  type: attribute
  prefix: /
  resource:
    path: ../src/Modules/
    namespace: Foodsharing\Modules

mock:
  type: attribute
  prefix: /mock
  resource:
    path: ../src/Mock/
    namespace: Foodsharing\Mock
  condition: "'%kernel.environment%' in ['dev', 'test']"
