#!/usr/bin/env bash

export FS_ENV=test

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

echo $SECONDS seconds elapsed

log-header "Preparing execution environment: Prepare PHP config & application"
bin/console foodsharing:setup
# configure path to application
# *https://forums.docker.com/t/sed-couldnt-open-temporary-file-xyz-permission-denied-when-using-virtiofs/125473/2
tmpfile=$(mktemp tmp_file_XXXXXX)
sed "s#/app#$CI_PROJECT_DIR#g" /usr/local/etc/php-fpm.d/fpm.conf > $tmpfile; cat $tmpfile > /usr/local/etc/php-fpm.d/fpm.conf; rm $tmpfile
# let PHP-FPM run as root
# sed -i "s#www-data#root#g" /usr/local/etc/php-fpm.d/fpm.conf
# disable xdebug
# rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

php-fpm -R 2> php_fpm_err.log &

log-header "Initializing database"
SECONDS=0
mysql -u root -proot -hdb --execute="drop database if exists foodsharing; create database foodsharing"
vendor/bin/phinx migrate
echo $SECONDS seconds elapsed

log-header "Starting mail queue worker"
php run.php Mails queueWorker &

log-header "Waiting for assets to be generated ..."
while ! [ "$(ls -A assets)" ];
do
sleep 1;
echo -ne ".";
done
echo

log-header "Create DB dump file for codeception"
mysqldump -uroot -proot -hdb foodsharing > dump.sql
pwd

log-header "Running tests"
vendor/bin/codecept run -s Acceptance --xml=report-code.xml --html=report-code.html
echo $SECONDS seconds elapsed
