#!/usr/bin/env bash

export FS_ENV=test

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

SUITE=$1 # 1st argument
TRIES=${2:-1} # 2nd argument, optional - amount of tries
GROUP=${3:-}  # 3rd argument, optional - group name

echo $SECONDS seconds elapsed

log-header "Preparing execution environment: Prepare PHP config, application & composer dev dependencies"
bin/console foodsharing:setup

# Configure PHP-FPM paths for CI
FPM_CONF=$(ls -1 /etc/php/*/fpm/php-fpm.conf 2>/dev/null)
sed -i "s#/app#${CI_PROJECT_DIR:?}#g" "$FPM_CONF"

# Start PHP-FPM in the background
php-fpm -R 2> php_fpm_err.log &

log-header "Initializing database"
SECONDS=0
mariadb -u root -proot -hdb --execute="drop database if exists foodsharing; create database foodsharing"
vendor/bin/phinx migrate
vendor/bin/codecept foodsharing:test-seed
echo $SECONDS seconds elapsed

log-header "Starting mail queue worker"
bin/console foodsharing:mailqueueworker &

log-header "Waiting for assets to be generated ..."
wait-for-assets

log-header "Create DB dump file for codeception"
mariadb-dump --user root --password=root -hdb foodsharing > dump.sql
pwd

log-header "Running tests"
failed=0
SECONDS=0

GROUP_PARAMS=""
if [ -n "$GROUP" ]; then
  GROUP_PARAMS="-g $GROUP"
fi

vendor/bin/codecept run "$SUITE" $GROUP_PARAMS --xml=report-"$SUITE"-0.xml --html=report-"$SUITE"-0.html || failed=1
echo $SECONDS seconds elapsed

if [ $failed -eq 0 ] # first run succeeded, we can finish early
then
  log-header "Done!"
  exit 0
fi

while [ $failed -le "$TRIES" ] # re-run failed tests $TRIES times
do
  log-header "Attempt $failed/$TRIES: check for codeception errors"
  # check if codeception generated a report file that contains failed tests
  # Otherwise, codeception probably failed itself and the whole job should fail
  grep -E '<error|<failure' tests/_output/report-"$SUITE"-$((failed - 1)).xml || \
    (echo "report.xml is incomplete, aborting" && false)

  log-header "Rerunning failed tests"
  SECONDS=0
  # create separate report files for each re-run so we don't overwrite the previous reports

  if vendor/bin/codecept run "$SUITE" $GROUP_PARAMS --xml=report-"$SUITE"-$failed.xml --html=report-"$SUITE"-$failed.html -g failed;
  then
    log-header "Done!"
    exit 0
  else
    ((failed++))
  fi
  echo $SECONDS seconds elapsed
done

# maximum tries reached
exit 1
