#!/usr/bin/env bash

export FS_ENV=test

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

echo $SECONDS seconds elapsed

log-header "Preparing execution environment: Prepare PHP config, application & composer dev dependencies"
bin/console foodsharing:setup
# configure path to application
# *https://forums.docker.com/t/sed-couldnt-open-temporary-file-xyz-permission-denied-when-using-virtiofs/125473/2
tmpfile=$(mktemp tmp_file_XXXXXX)
sed "s#/app#$CI_PROJECT_DIR#g" /usr/local/etc/php-fpm.d/fpm.conf > $tmpfile; cat $tmpfile > /usr/local/etc/php-fpm.d/fpm.conf; rm $tmpfile
# let PHP-FPM run as root
# sed -i "s#www-data#root#g" /usr/local/etc/php-fpm.d/fpm.conf
# disable xdebug
# rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

php-fpm -R 2> php_fpm_err.log &

log-header "Initializing database"
SECONDS=0
mariadb -u root -proot -hdb --execute="drop database if exists foodsharing; create database foodsharing"
bin/console foodsharing:mailqueueworker &
vendor/bin/phinx migrate
echo $SECONDS seconds elapsed

log-header "Waiting for assets to be generated ..."
while ! [ "$(ls -A assets)" ];
do
sleep 1;
echo -ne ".";
done
echo

log-header "Create DB dump file for codeception"
mariadb-dump --user root --password=root -hdb foodsharing > dump.sql
pwd

log-header "Running tests"
cd tests/e2e || exit 1
npm ci
npx playwright install
PLAYWRIGHT_JUNIT_OUTPUT_NAME=tests/_output/report-playwright.xml npx playwright test --reporter=junit
