#!/usr/bin/env bash

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

declare -r base_dir=$(cd "$dir/.." && pwd)

if [[ -n "${1:-}" && "$1" =~ ^(full|all)$ ]]; then
  log-header "Removing containers and images"
  FS_ENV="test"
  "$dir"/docker-compose down --volumes --remove-orphans
  FS_ENV="dev"
  "$dir"/docker-compose down --rmi all --volumes --remove-orphans
else
  log-header "Removing containers"
  FS_ENV="dev"
  "$dir"/docker-compose down --volumes --remove-orphans
  FS_ENV="test"
  "$dir"/docker-compose down --volumes --remove-orphans
fi

if [[ -n "${1:-}" && "$1" =~ ^(full|all|modules)$ ]]; then
  log-header "Removing local node_modules"
  find "$base_dir" -name "node_modules" -type d -prune | xargs du -chs # prints the folders
  find "$base_dir" -name "node_modules" -type d -prune -exec rm -rf '{}' + # removes the folders
fi

log-header "Removing directories"

      rm -rf \
        "$base_dir"/assets \
        "$base_dir"/images \
        "$base_dir"/data \
        "$base_dir"/cache \
        "${base_dir:?}"/var \
        "$base_dir"/tmp \
        "$base_dir"/tests/_output \
        "$base_dir"/docs/data/api_dump.json\
        "$base_dir"/docs/data/build \
        "$base_dir"/docs/.vitepress/dist \
        "$base_dir"/docs/.vitepress/cache \
        "$base_dir"/docs/.vitepress/.temp \
        "$base_dir"/docs/.npm

log-header "All clean!"
