#!/usr/bin/env bash
dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh
FS_ENV="${1:-dev}"

log-header "Clear assets ..."
rm -rf "$(cd "$dir/.." && pwd)"/assets/*

log-header "Restarting $FS_ENV containers ..."
"$dir"/docker-compose restart

log-header "Waiting for assets to be generated ..."
wait-for-assets
exec-in-container app bin/console assets:install

if ([ "$FS_ENV" == "dev" ] ); then
    "$dir"/__helping-print-intro.sh
fi