#!/usr/bin/env bash

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

log-header "Waiting for database ..."
wait-for-mysql

log-header "Drop DB ..."
dropdb foodsharing

log-header "Creating DB ..."
createdb foodsharing

log-header "Migrating DB ..."
migratedb

log-header "Create docs data ..."
"$dir"/dev-docs-build

log-header "Seed DB ..."
exec-in-container app vendor/bin/codecept foodsharing:seed "$@"

log-header "Running daily cronjob..."
exec-in-container app bin/console foodsharing:daily-cronjob

log-header "Running stats ..."
exec-in-container app bin/console foodsharing:stats

log-header "All done"
