#!/usr/bin/env bash

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

log-header "Seed DB ..."
exec-in-container app vendor/bin/codecept foodsharing:seed "$@"

log-header "Running daily cronjob..."
exec-in-container app bin/console foodsharing:maintenance:regions
exec-in-container app bin/console foodsharing:maintenance:bells
exec-in-container app bin/console foodsharing:maintenance:stores
exec-in-container app bin/console foodsharing:maintenance:cleanup1
exec-in-container app bin/console foodsharing:maintenance:cleanup2

log-header "Running stats ..."
exec-in-container app bin/console foodsharing:stats

log-header "All done"

if ([ "$FS_ENV" == "dev" ] ); then
    "$dir"/__helping-print-intro.sh
fi
