#!/usr/bin/env bash

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

log-header "Preparing execution environment: Prepare PHP config & application"
exec-in-container app 'bin/console foodsharing:setup'

log-header "Configuring PHP-FPM"
exec-in-container app 'tmpfile=$(mktemp tmp_file_XXXXXX); sed "s#/app#$CI_PROJECT_DIR#g" /usr/local/etc/php-fpm.d/fpm.conf > "$tmpfile"; cat "$tmpfile" > /usr/local/etc/php-fpm.d/fpm.conf; rm "$tmpfile"'

log-header "Initializing database"
exec-in-container app 'mysql -u root -proot -hdb --execute="drop database if exists foodsharing; create database foodsharing"'
exec-in-container app 'vendor/bin/phinx migrate'

log-header "Build database documentation"
exec-in-container docs "/app/scripts/generate-documentation/mysql_generate_documentation"

log-header "Load API Dump"
exec-in-container app 'bin/console nelmio:apidoc:dump --format=json > docs/data/api_dump.json'
