#!/usr/bin/env bash
# run docker-compose with the container specified by $FS_ENV and a suitable project name
# which command to run by docker-compose and additional arguments is specified by the arguments
# of this script

# Export the current host operating system to FS_PLATFORM
unameOut="$(uname -s)"
case "${unameOut}" in
    Darwin*)    export FS_PLATFORM=mac;;
    *)          export FS_PLATFORM=default;;
esac

# check if gp is there
if [[ $(type -t gp) == file ]];
then
    FS_PLATFORM=gitpod
fi

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

function _docker-compose () {
    # On newer systems, docker-compose may not be available anymore.
    # It's been substituted by "docker compose" (with a space inbetween).
    if docker compose version >/dev/null 2>&1; then
        docker compose "$@"
    elif command -v docker-compose >/dev/null; then
        docker-compose "$@"
    else
        echo "docker compose not found. Please install latest docker version"
        exit 1
    fi
}

zammad_files=""
if [ "${ZAMMAD:-false}" = "true" ]; then
    zammad_files="--file $dir/../docker/zammad/docker-compose.yml --env-file $dir/../docker/zammad/.env"
fi

listmonk_files=""
if [ "${LISTMONK:-false}" = "true" ]; then
    listmonk_files="--file $dir/../docker/listmonk/docker-compose.yml"
fi

_docker-compose \
    --file "$dir"/../docker/docker-compose.yml \
    --file "$dir"/../docker/docker-compose."$FS_ENV".yml \
    $zammad_files \
    $listmonk_files \
    --project-name foodsharing_"$FS_ENV" \
    "$@"
