#!/usr/bin/env bash

export FS_ENV=test

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

# Client unit tests moved to Playwright (see ./scripts/test-e2e); this now lints only.
log-header "Linting client js"
run-in-container client 'yarn && yarn lint'
