#!/usr/bin/env bash

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

log-header "Running client e2e tests with playwright"
cd tests/e2e
npm ci && npx playwright install
PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:3005/ npx playwright test
