services:
  # Keila, platform for sending newsletters
  keila:
    container_name: foodsharing_dev_keila
    image: pentacent/keila:latest
    depends_on:
      - keila-postgres
      - maildev
    expose:
      - 4000
    ports:
      - "18088:4000"
    environment:
      SECRET_KEY_BASE: "BoA21ya57mC4gKzUv4tjuRsWduN2vBnojE1hj4XKVohVQLIkUHyk8ICSGNjJTztC"
      DB_URL: "postgres://postgres:postgres@keila-postgres/postgres"
      URL_HOST: "localhost"
      KEILA_USER: "root@localhost"
      KEILA_PASSWORD: "rootpassword"
      MAILER_SMTP_HOST: "maildev"
      MAILER_SMTP_PORT: 1025
      MAILER_SMTP_FROM_EMAIL: "noreply@foodsharing.network"
      MAILER_SMTP_PASSWORD: ""

  # PostgreSQL database for Keila
  keila-postgres:
    container_name: foodsharing_dev_keila_postgres
    image: postgres:alpine
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
