#!/usr/bin/env bash

set -o errexit

dir=$(dirname "$0")
root="$dir/../.."
# shellcheck source=./__common.sh
source "$dir/../__common.sh"

BUILD_DIR="$root/docs/data/build"
RESULT_FOLDER="$root/docs/en/backend/database"
META_DATA_FILE="$root/docs/data/database_metadata.json"

# Set node module path to global modules
NODE_PATH=$(npm root -g)
export NODE_PATH
# prepare processing folder
mkdir -p "$BUILD_DIR"

# Extract database schema directly from database
SCHEMA_JSON_FILE="$BUILD_DIR/schema.json"
echo "Extracting schema from database..."
node "$dir/generate-documentation/extract_schema_from_db.js" "$BUILD_DIR"

# Extract modules and table usage from code base
TABLE_USAGE_FILE="$BUILD_DIR/extract_tables_usage_from_php.grep_result"
MODULE_FILE="$BUILD_DIR/modules.json"
grep --include=\*.php -E "([^\$]fs_[a-zA-Z0-9_]+)" -R -B5 -A 2 -n "$root/src" > "$TABLE_USAGE_FILE"
node "$dir/generate-documentation/extract_tables_usage_from_php_parser.js"  "$BUILD_DIR" "$TABLE_USAGE_FILE" "$MODULE_FILE"

# Transform schema and usage information to documentation
node "$dir/generate-documentation/sql_to_documentation.js" "$BUILD_DIR" "$RESULT_FOLDER" "$SCHEMA_JSON_FILE" "$META_DATA_FILE" "$MODULE_FILE"

echo
echo "GENERATION COMPLETE"
