#!/usr/bin/env sh

TEST_DIRECTORY="tests/e2e/"

STAGED_TEST_FILES=$(git diff --cached --name-only --diff-filter=d | grep ${TEST_DIRECTORY}) || true

if [ "$STAGED_TEST_FILES" != "" ]; then
    cd ${TEST_DIRECTORY} || exit 1
    npm run lint && npm run prettier
fi
